#
# Expose MPS internal endpoint
#
kind: Service
apiVersion: v1
metadata:
    name: mps-service
    namespace: {{ .Release.Namespace }}
    labels:
        app: mps
        release: {{ .Release.Name }}
spec:
    selector:
        app: mps
    ports:
    - name: mps-port
      port: 9910
      targetPort: 9910
    type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: mps-ingress
    namespace: {{ .Release.Namespace }}
    labels:
        release: {{ .Release.Name }}
    annotations:
        nginx.ingress.kubernetes.io/affinity: 'cookie'
spec:
    rules:
      - http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                  service:
                      name: mps-service
                      port:
                          number: 9910

